# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  apt_packages:
    - cmake
    - doxygen
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install -r docs/requirements.txt
    build:
      html:
        - cmake . -DBUILD_DOCS:BOOL=ON -DBUILD_WEIF:BOOL=OFF -DBUILD_TESTS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DSPHINX_OUTPUT:PATH=$READTHEDOCS_OUTPUT/html/ -B build 
        - cmake --build build --target docs
