name: Build project and run ctest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    name: Build with ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "GCC 14"
            container: gcc:14
          - name: "GCC 15"
            container: gcc:15
          - name: "Clang 20"
            container: silkeh/clang:20

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake curl doxygen git libtool unzip pkg-config tar zip

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_BINARY_SOURCES: default,readwrite

    - name: Restore vcpkg cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{matrix.container}}-${{runner.arch}}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{matrix.container}}-${{runner.arch}}-

    - name: Configure CMake
      run: cmake -B ${GITHUB_WORKSPACE}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${GITHUB_WORKSPACE}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc) --verbose

    - name: Test
      run: ctest --test-dir ${GITHUB_WORKSPACE}/build --build-config ${{env.BUILD_TYPE}} --verbose

    - name: Save vcpkg cache
      uses: actions/cache/save@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{matrix.container}}-${{runner.arch}}-${{ hashFiles('vcpkg.json') }}
